### PR TITLE
Allow following of symlinks

### PR DESCRIPTION
**Pull request by ghost**
This commit adds a configuration option to allow following of symlinks. A common backup strategy is to make a directory containing symlinks to a subset of files that should be backed up.

For instance, consider the following:

```bash
➜  [clocks]: ~ ls -al /icebox/InTheCloud 
total 1.0K
lrwxrwxrwx 1 rdahlgren rdahlgren  13 Mar 20 18:02 Audio -> /icebox/Audio
lrwxrwxrwx 1 rdahlgren rdahlgren  13 Mar 20 18:02 Books -> /icebox/Books
lrwxrwxrwx 1 rdahlgren rdahlgren  16 Mar 20 18:03 Pictures -> /icebox/Pictures
-rw-r--r-- 1 rdahlgren rdahlgren 127 Mar 20 17:43 README
```

The `InTheCloud` folder allows me to designate a subset of the contents of the `/icebox` drive for uploading to the cloud.

I implemented this by using a variable in the config file. If `FOLLOW_SYMLINKS` is set to any value other than 'no', the `--no-follow-symlinks` switch will be omitted. I have also updated the template to set this configuration value to `no` so that the current behavior is unchanged.

### CODE REVIEW

**Comment by famzah** [comment]
Hi. I agree that this is very convenient.

For the sake of backward compatibility with existing configurations, shouldn't the default be "don't follow symlinks" (even without stating this explicitly in the config)?

This way, if a user wants to use the new feature they must state this explicitly in their existing or new config files?

**Comment by ghost** [comment]
Makes sense, I'll update

**Comment by ghost** [comment]
I've updated the branch so that a missing config value means that the current behavior of not following symlinks will occur. I've also swapped the conditional so that only an explicit 'yes' will cause symlinks to be followed.

**Comment by ghost** [comment]
Are there additional changes you'd like before accepting this PR?

**Comment by famzah** [comment]
I'm sorry for the delay. Personal life overwhelmed me. :) I'll take a look into the final PR this week.

**Comment by famzah** [comment]
Thank you for your contribution!

**Pull request merged**
